default: &default
  adapter: postgresql
  encoding: unicode
  database: tapedeckDB
  host: db
  port: 5432
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tapedeckDB_development
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: tapedeckDB_development
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  <<: *default
  database: tapedeckDB_development
  password: <%= ENV['POSTGRES_PASSWORD'] %>